In [163]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [164]:
dfx = pd.read_csv("Diabetes_XTrain.csv")
dfy = pd.read_csv("Diabetes_YTrain.csv")

In [165]:
dfx.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            7      168             88             42      321  38.2   
1            8      110             76              0        0  27.8   
2            7      147             76              0        0  39.4   
3            2      100             66             20       90  32.9   
4            4      129             86             20      270  35.1   

   DiabetesPedigreeFunction  Age  
0                     0.787   40  
1                     0.237   58  
2                     0.257   43  
3                     0.867   28  
4                     0.231   23

In [166]:
dfy.head()

Outcome
0        1
1        0
2        1
3        1
4        0

In [167]:
X=dfx
Y=dfy.values
Y= Y.reshape(-1,)

In [175]:
#without scaling
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.35, random_state=2)
knn = KNeighborsClassifier(n_neighbors=25, metric='euclidean')
knn.fit(X_train,Y_train)
Y_pred = knn.predict(X_test)
confusion_matrix(Y_test, Y_pred)


array([[121,  13],
       [ 36,  32]], dtype=int64)

In [176]:
print("Without using scaling acuracy:")
acc = accuracy_score(Y_test, Y_pred)
acc*100

Without using scaling acuracy:


75.74257425742574

In [177]:
#standard scaling
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [178]:
# define standard scaler
std_scaler = StandardScaler()
# transform data
std_scaled = std_scaler.fit_transform(X)
print(std_scaled)

[[ 0.97457151  1.52528095  0.94599501 ...  0.78036618  0.907501
   0.59363371]
 [ 1.27524274 -0.31683408  0.35393439 ... -0.49918316 -0.72639999
   2.11034006]
 [ 0.97457151  0.85830827  0.35393439 ...  0.92800649 -0.66698541
   0.8464181 ]
 ...
 [-0.52878465  0.06429317 -0.43547977 ... -0.25311598  0.69954996
  -0.92307263]
 [ 0.07255781  1.0806325   0.15658085 ... -0.06856559 -0.42635635
   0.34084932]
 [-0.82945588 -1.01556737  0.45261116 ...  0.01755792 -0.34614667
  -0.33324239]]


In [35]:
#MinMax scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(X)
print(x_scaled)


[[0.41176471 0.84422111 0.72131148 ... 0.56929955 0.30273271 0.31666667]
 [0.47058824 0.55276382 0.62295082 ... 0.414307   0.06789069 0.61666667]
 [0.41176471 0.73869347 0.62295082 ... 0.58718331 0.0764304  0.36666667]
 ...
 [0.11764706 0.61306533 0.49180328 ... 0.44411326 0.27284372 0.01666667]
 [0.23529412 0.77386935 0.59016393 ... 0.46646796 0.11101623 0.26666667]
 [0.05882353 0.44221106 0.63934426 ... 0.47690015 0.12254483 0.13333333]]


In [179]:
#Max Abs scaling
from sklearn.preprocessing import MaxAbsScaler
max_abs_scaler = MaxAbsScaler()
maxabs_scaled = max_abs_scaler.fit_transform(X)
print(maxabs_scaled)

[[0.41176471 0.84422111 0.72131148 ... 0.56929955 0.32520661 0.49382716]
 [0.47058824 0.55276382 0.62295082 ... 0.414307   0.09793388 0.71604938]
 [0.41176471 0.73869347 0.62295082 ... 0.58718331 0.10619835 0.5308642 ]
 ...
 [0.11764706 0.61306533 0.49180328 ... 0.44411326 0.29628099 0.27160494]
 [0.23529412 0.77386935 0.59016393 ... 0.46646796 0.13966942 0.45679012]
 [0.05882353 0.44221106 0.63934426 ... 0.47690015 0.15082645 0.35802469]]


In [180]:
#Robust Scaling
from sklearn.preprocessing import RobustScaler
robust_scaler = RobustScaler()
r_scaled = robust_scaler.fit_transform(X)
print(r_scaled)


[[ 0.8         1.3         0.88888889 ...  0.63589744  1.03049555
   0.6875    ]
 [ 1.         -0.15        0.22222222 ... -0.43076923 -0.36721728
   1.8125    ]
 [ 0.8         0.775       0.22222222 ...  0.75897436 -0.31639136
   0.875     ]
 ...
 [-0.2         0.15       -0.66666667 ... -0.22564103  0.85260483
  -0.4375    ]
 [ 0.2         0.95        0.         ... -0.07179487 -0.11054638
   0.5       ]
 [-0.4        -0.7         0.33333333 ...  0.         -0.04193139
   0.        ]]


In [181]:
X_train, X_test, Y_train, Y_test = train_test_split(std_scaled, Y, test_size=0.35, random_state=2)


In [182]:
knn = KNeighborsClassifier(n_neighbors=25, metric='euclidean')
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='uniform')

In [183]:
Y_pred = knn.predict(X_test)

In [184]:
confusion_matrix(Y_test, Y_pred)

array([[129,   5],
       [ 41,  27]], dtype=int64)

In [185]:
print("Standard scaler acuracy:")
acc = accuracy_score(Y_test, Y_pred)
acc*100

Standard scaler acuracy:


77.22772277227723

In [204]:
#min max scale
X_train, X_test, Y_train, Y_test = train_test_split(x_scaled, Y, test_size=0.35, random_state=2)
knn = KNeighborsClassifier(n_neighbors=29, metric='euclidean')
knn.fit(X_train,Y_train)
Y_pred = knn.predict(X_test)
confusion_matrix(Y_test, Y_pred)


array([[129,   5],
       [ 45,  23]], dtype=int64)

In [205]:
print("MinMax scaler acuracy:")
acc = accuracy_score(Y_test, Y_pred)
acc*100

MinMax scaler acuracy:


75.24752475247524

In [224]:
#Max Abs scale
X_train, X_test, Y_train, Y_test = train_test_split(maxabs_scaled, Y, test_size=0.35, random_state=2)
knn = KNeighborsClassifier(n_neighbors=41, metric='euclidean')
knn.fit(X_train,Y_train)
Y_pred = knn.predict(X_test)
confusion_matrix(Y_test, Y_pred)


array([[131,   3],
       [ 47,  21]], dtype=int64)

In [225]:
print("MaxAbs scaler acuracy:")
acc = accuracy_score(Y_test, Y_pred)
acc*100

MaxAbs scaler acuracy:


75.24752475247524

In [226]:
#Robust Scaler accuracy
X_train, X_test, Y_train, Y_test = train_test_split(r_scaled, Y, test_size=0.35, random_state=2)
knn = KNeighborsClassifier(n_neighbors=25, metric='euclidean')
knn.fit(X_train,Y_train)
Y_pred = knn.predict(X_test)
confusion_matrix(Y_test, Y_pred)


array([[125,   9],
       [ 40,  28]], dtype=int64)

In [227]:
print("Robust scaler acuracy:")
acc = accuracy_score(Y_test, Y_pred)
acc*100

Robust scaler acuracy:


75.74257425742574