In [227]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [228]:
dfx = pd.read_csv("Diabetes_XTrain.csv")
dfy = pd.read_csv("Diabetes_YTrain.csv")
dfx

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              7      168             88             42      321  38.2   
1              8      110             76              0        0  27.8   
2              7      147             76              0        0  39.4   
3              2      100             66             20       90  32.9   
4              4      129             86             20      270  35.1   
..           ...      ...            ...            ...      ...   ...   
571            2      111             60              0        0  26.2   
572            7      187             68             39      304  37.7   
573            2      122             60             18      106  29.8   
574            4      154             72             29      126  31.3   
575            1       88             78             29       76  32.0   

     DiabetesPedigreeFunction  Age  
0                       0.787   40  
1                       0.237   58  
2                       0.257   43  
3                       0.867   28  
4                       0.231   23  
..                        ...  ...  
571                     0.343   23  
572                     0.254   41  
573                     0.717   22  
574                     0.338   37  
575                     0.365   29  

[576 rows x 8 columns]

In [229]:
dfx.head()
dfx['BMI']= dfx['BMI']*10
dfx['DiabetesPedigreeFunction']=dfx['DiabetesPedigreeFunction']*1000
dfx

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0              7      168             88             42      321  382.0   
1              8      110             76              0        0  278.0   
2              7      147             76              0        0  394.0   
3              2      100             66             20       90  329.0   
4              4      129             86             20      270  351.0   
..           ...      ...            ...            ...      ...    ...   
571            2      111             60              0        0  262.0   
572            7      187             68             39      304  377.0   
573            2      122             60             18      106  298.0   
574            4      154             72             29      126  313.0   
575            1       88             78             29       76  320.0   

     DiabetesPedigreeFunction  Age  
0                       787.0   40  
1                       237.0   58  
2                       257.0   43  
3                       867.0   28  
4                       231.0   23  
..                        ...  ...  
571                     343.0   23  
572                     254.0   41  
573                     717.0   22  
574                     338.0   37  
575                     365.0   29  

[576 rows x 8 columns]

In [230]:
dfy.head()

Outcome
0        1
1        0
2        1
3        1
4        0

In [231]:
X=dfx.values
Y=dfy.values
Y= Y.reshape(-1,)

In [232]:
X=np.round(X)
X=X.astype(int)
print(X)
print(Y)

[[  7 168  88 ... 382 787  40]
 [  8 110  76 ... 278 237  58]
 [  7 147  76 ... 394 257  43]
 ...
 [  2 122  60 ... 298 717  22]
 [  4 154  72 ... 313 338  37]
 [  1  88  78 ... 320 365  29]]
[1 0 1 1 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1
 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1
 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 1 1 1
 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0
 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 0
 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0
 0 0 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0 1 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0
 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 1 1 1 0 1 1 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0

In [233]:
std_scaler = StandardScaler()
# transform data
x_scaled = std_scaler.fit_transform(X)
print(x_scaled)

[[ 0.97457151  1.52528095  0.94599501 ...  0.78036618  0.907501
   0.59363371]
 [ 1.27524274 -0.31683408  0.35393439 ... -0.49918316 -0.72639999
   2.11034006]
 [ 0.97457151  0.85830827  0.35393439 ...  0.92800649 -0.66698541
   0.8464181 ]
 ...
 [-0.52878465  0.06429317 -0.43547977 ... -0.25311598  0.69954996
  -0.92307263]
 [ 0.07255781  1.0806325   0.15658085 ... -0.06856559 -0.42635635
   0.34084932]
 [-0.82945588 -1.01556737  0.45261116 ...  0.01755792 -0.34614667
  -0.33324239]]


In [234]:
print(X.dtype,Y.dtype)


int32 int64


In [235]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

# Test Time 
def knn(X,Y,queryPoint,k=5):
    
    vals = []
    m = X.shape[0]
    
    for i in range(m):
        d = dist(queryPoint,X[i])
        vals.append((d,Y[i]))
        
    
    vals = sorted(vals)
    # Nearest/First K points
    vals = vals[:k]
    
    vals = np.array(vals)
    
    #print(vals)
    
    new_vals = np.unique(vals[:,1],return_counts=True)
    #print(new_vals)
    
    index = new_vals[1].argmax()
    pred = new_vals[0][index]
    
    return pred

In [236]:
X_test= pd.read_csv("Diabetes_Xtest.csv")
X_test


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              0      180             90             26       90  36.5   
1              2       93             64             32      160  38.0   
2              2      114             68             22        0  28.7   
3             13       76             60              0        0  32.8   
4              1       80             74             11       60  30.0   
..           ...      ...            ...            ...      ...   ...   
187           10      108             66              0        0  32.4   
188            3      130             64              0        0  23.1   
189            0      162             76             36        0  49.6   
190           12       84             72             31        0  29.7   
191            0       94              0              0        0   0.0   

     DiabetesPedigreeFunction  Age  
0                       0.314   35  
1                       0.674   23  
2                       0.092   25  
3                       0.180   41  
4                       0.527   22  
..                        ...  ...  
187                     0.272   42  
188                     0.314   22  
189                     0.364   26  
190                     0.297   46  
191                     0.256   25  

[192 rows x 8 columns]

In [237]:
X_test['BMI']=X_test['BMI']*10
X_test['DiabetesPedigreeFunction']=X_test['DiabetesPedigreeFunction']*1000
X_test


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0              0      180             90             26       90  365.0   
1              2       93             64             32      160  380.0   
2              2      114             68             22        0  287.0   
3             13       76             60              0        0  328.0   
4              1       80             74             11       60  300.0   
..           ...      ...            ...            ...      ...    ...   
187           10      108             66              0        0  324.0   
188            3      130             64              0        0  231.0   
189            0      162             76             36        0  496.0   
190           12       84             72             31        0  297.0   
191            0       94              0              0        0    0.0   

     DiabetesPedigreeFunction  Age  
0                       314.0   35  
1                       674.0   23  
2                        92.0   25  
3                       180.0   41  
4                       527.0   22  
..                        ...  ...  
187                     272.0   42  
188                     314.0   22  
189                     364.0   26  
190                     297.0   46  
191                     256.0   25  

[192 rows x 8 columns]

In [238]:
X_test= X_test.values
X_test=np.round(X_test)
X_test= X_test.astype(int)
X_test

array([[  0, 180,  90, ..., 365, 314,  35],
       [  2,  93,  64, ..., 380, 674,  23],
       [  2, 114,  68, ..., 287,  92,  25],
       ...,
       [  0, 162,  76, ..., 496, 364,  26],
       [ 12,  84,  72, ..., 297, 297,  46],
       [  0,  94,   0, ...,   0, 256,  25]])

In [239]:
t_scaled = std_scaler.fit_transform(X_test)
print(t_scaled)

[[-1.18069959  1.69935671  1.23607139 ...  0.58057039 -0.41297962
   0.07934011]
 [-0.60533329 -0.92436586 -0.36623149 ...  0.79289327  0.73998714
  -0.97730508]
 [-0.60533329 -0.29105352 -0.11972335 ... -0.52350861 -1.12397579
  -0.80119755]
 ...
 [-1.18069959  1.15651756  0.37329292 ...  2.43485691 -0.25284534
  -0.71314378]
 [ 2.27149819 -1.19578544  0.12678478 ... -0.38196002 -0.46742527
   1.04793154]
 [-1.18069959 -0.89420813 -4.31036164 ... -4.58595313 -0.59873537
  -0.80119755]]


In [289]:
p= X_test.shape[0]
arr=[]
for i in range(p):
    x= knn(x_scaled,Y, t_scaled[i],25)
    arr.append(x)
arr= np.array(arr)    
print(arr)  


[1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1.
 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [290]:
arr= arr.astype(int)
df= pd.DataFrame(arr)
df.columns= ['Outcome']
df

Outcome
0          1
1          0
2          0
3          0
4          0
..       ...
187        0
188        0
189        0
190        0
191        0

[192 rows x 1 columns]

In [291]:
df.to_csv('Y_predi.csv', index=False)